spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emergencyvehicle?useSSL=false
      username: root
      password: ns2002577


   jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true





